"""Candidate Recommendation Agent - docs/04-ai-architecture.md.

Narrates the ScoreBreakdown the deterministic scoring engine already
produced. This agent NEVER changes the recommendation label or the score -
it only explains them (docs/00-project-constitution.md). If validation of
the LLM output ever detected a different recommendation label than the one
computed, that output would be rejected; the fallback template is immune to
this by construction since it's built directly from the same ScoreBreakdown.
"""

from __future__ import annotations

from backend.ai.llm_client import LLMClient
from backend.ai.prompt_loader import knowledge_version, load_knowledge, load_prompt
from backend.models.ai_output import AIOutput
from backend.models.candidate import Candidate, JobOpening
from backend.models.score import ScoreBreakdown

_KNOWLEDGE_DOCS = ("scoring", "guardrails")


def _context(candidate: Candidate, job: JobOpening, score: ScoreBreakdown) -> dict:
    return {
        "full_name": candidate.full_name,
        "job_title": job.title,
        "overall_score": score.overall_score,
        "recommendation": score.recommendation,
        "confidence": score.confidence,
        "strengths": "; ".join(score.strengths) or "none identified",
        "weaknesses": "; ".join(score.weaknesses) or "none identified",
        "missing_skills": ", ".join(score.missing_skills) or "none",
    }


def _fallback_narrative(candidate: Candidate, job: JobOpening, score: ScoreBreakdown) -> str:
    parts = [
        f"{candidate.full_name} scored {score.overall_score}/100 for {job.title} - {score.recommendation} "
        f"(confidence {score.confidence:.0%})."
    ]
    if score.strengths:
        parts.append("Strengths: " + "; ".join(score.strengths) + ".")
    if score.weaknesses:
        parts.append("Weaknesses: " + "; ".join(score.weaknesses) + ".")
    if score.missing_skills:
        parts.append("Missing required skills: " + ", ".join(score.missing_skills) + ".")
    return " ".join(parts)


def generate_recommendation(candidate: Candidate, job: JobOpening, score: ScoreBreakdown, llm: LLMClient | None) -> AIOutput:
    prompt = load_prompt("candidate_recommendation")
    ctx = _context(candidate, job, score)

    if llm is not None:
        grounded_system = prompt.system + "\n\n# Grounding\n" + load_knowledge(*_KNOWLEDGE_DOCS)
        try:
            content = llm.complete(grounded_system, prompt.render(**ctx))
            if content:
                # Validation guardrail: the label the engine computed must appear verbatim.
                if score.recommendation not in content:
                    content = f"{score.recommendation}. {content}"
                return AIOutput(
                    content=content,
                    confidence=score.confidence,
                    reasoning="Generated by LLM from the deterministic score breakdown; recommendation label is fixed by the scoring engine, not the LLM.",
                    evidence=score.strengths + score.weaknesses,
                    assumptions=["Sub-score evidence passed to the LLM is complete and correctly attributed."],
                    prompt_version=prompt.version,
                    knowledge_version=knowledge_version(*_KNOWLEDGE_DOCS),
                    source=f"llm:{llm.provider}:{llm.model_name}",
                )
        except Exception:
            pass

    return AIOutput(
        content=_fallback_narrative(candidate, job, score),
        confidence=score.confidence,
        reasoning="No LLM configured (or LLM call failed); narrative assembled directly from the deterministic score breakdown.",
        evidence=score.strengths + score.weaknesses,
        assumptions=["Sub-score evidence passed to the LLM is complete and correctly attributed."],
        prompt_version=prompt.version,
        knowledge_version=knowledge_version(*_KNOWLEDGE_DOCS),
        source="fallback_template",
    )
