"""Candidate Summary Agent — docs/04-ai-architecture.md.

Produces a short recruiter-facing summary. Uses an LLM if one is configured
(backend/ai/llm_client.py); otherwise falls back to a deterministic template
built directly from the candidate/LinkedIn/job fields, so the pipeline never
depends on an API key to run end-to-end (docs/00-project-constitution.md).
"""

from __future__ import annotations

from backend.ai.llm_client import LLMClient
from backend.ai.prompt_loader import knowledge_version, load_knowledge, load_prompt
from backend.models.ai_output import AIOutput
from backend.models.candidate import Candidate, JobOpening

_KNOWLEDGE_DOCS = ("company", "scoring", "guardrails")


def _context(candidate: Candidate, job: JobOpening) -> dict:
    li = candidate.linkedin
    return {
        "full_name": candidate.full_name,
        "current_title": (li.current_title if li else candidate.attendee.title) or "Unknown",
        "current_company": (li.current_company if li else candidate.attendee.company) or "Unknown",
        "years_experience": f"{li.years_experience:.0f}" if li and li.years_experience is not None else "unknown",
        "top_skills": ", ".join(li.top_skills) if li and li.top_skills else "not available",
        "industry": (li.industry if li else "") or "not available",
        "conference_name": candidate.attendee.conference_name,
        "conference_domain": candidate.attendee.conference_domain,
        "notes": candidate.attendee.notes or "none",
        "job_title": job.title,
        "job_seniority": job.seniority,
        "job_department": job.department,
        "required_skills": ", ".join(job.required_skills),
    }


def _fallback_summary(candidate: Candidate, job: JobOpening) -> str:
    li = candidate.linkedin
    if li is None:
        return (
            f"{candidate.full_name} — {candidate.attendee.title} at {candidate.attendee.company}. "
            f"Met at {candidate.attendee.conference_name}. No LinkedIn match found, so skills and "
            f"experience could not be verified; treat as a lower-confidence lead for {job.title}."
        )
    skills = ", ".join(li.top_skills[:5]) if li.top_skills else "no listed skills"
    return (
        f"{candidate.full_name} is a {li.current_title} at {li.current_company} with "
        f"{li.years_experience:.0f} years of experience in {li.industry or 'their field'}. "
        f"Key skills: {skills}. Met at {candidate.attendee.conference_name}. "
        f"Being evaluated for {job.title} ({job.seniority}, {job.department})."
    )


def generate_summary(candidate: Candidate, job: JobOpening, llm: LLMClient | None) -> AIOutput:
    prompt = load_prompt("candidate_summary")
    ctx = _context(candidate, job)

    if llm is not None:
        grounded_system = prompt.system + "\n\n# Grounding\n" + load_knowledge(*_KNOWLEDGE_DOCS)
        try:
            content = llm.complete(grounded_system, prompt.render(**ctx))
            if content:
                return AIOutput(
                    content=content,
                    confidence=0.8 if candidate.linkedin else 0.5,
                    reasoning="Generated by LLM, grounded in candidate/job context and company knowledge base.",
                    evidence=[ctx["top_skills"], ctx["current_title"]],
                    assumptions=["LinkedIn data (if present) is accurate and current."],
                    prompt_version=prompt.version,
                    knowledge_version=knowledge_version(*_KNOWLEDGE_DOCS),
                    source=f"llm:{llm.provider}:{llm.model_name}",
                )
        except Exception:
            pass  # fall through to deterministic fallback — never let an AI failure break the pipeline

    return AIOutput(
        content=_fallback_summary(candidate, job),
        confidence=0.6 if candidate.linkedin else 0.35,
        reasoning="No LLM configured (or LLM call failed); generated from a deterministic template over the candidate's structured fields.",
        evidence=[ctx["top_skills"], ctx["current_title"]],
        assumptions=["LinkedIn data (if present) is accurate and current."],
        prompt_version=prompt.version,
        knowledge_version=knowledge_version(*_KNOWLEDGE_DOCS),
        source="fallback_template",
    )
